--Create user table

--Create task table
CREATE TABLE IF NOT EXISTS skent.task
(
	task_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	task_name character varying NOT NULL,
	task_description character varying,
	task_value integer NOT NULL,
    task_icon character varying,
	CONSTRAINT task_pkey PRIMARY KEY (task_id)
);

--Fill task table
INSERT INTO skent.task
(
	task_name,
	task_description,
	task_value,
	task_icon
)
VALUES
('personal hygiene', 'Shower daily.', 1, '🧼'),
('school', 'Finish homeschool assignments.', 2, '📚'),
('goals', 'Work on your personal goals from Children and Youth Initiative', 1, '⭐'),
('pets', 'Feed a pet', 1, '🐶'),
('laundry', 'Hang the laundry.', 1, '👕'),
('garbage', 'Throw away the garbage.', 1,'🚮'),
('mikey', 'Clean Mikey tank.', 5, '🐢'),
('dishes', 'Help wash dishes at least once a day.', 1, '🍽️'),
('help', 'Help clean the house. Clean a common room spending at least 5 minutes.', 1, '🧹'),
('physical', 'Spend time outdoors. Tend to plants in the garden, walk to Seminary, exercise.', 1, '🏃🏽‍♂️'),
('extra', 'Do something nice for someone.', 1, '💝');

--Create assignment table
CREATE TABLE IF NOT EXISTS skent.assignment
(
	assign_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	task_id INTEGER NOT NULL,
	user_id INTEGER NOT NULL,
	CONSTRAINT assignment_pkey PRIMARY KEY (assign_id)
);

-- Create relationship between assignment, task, and user
ALTER TABLE IF EXISTS skent.assignment
ADD CONSTRAINT fk_task FOREIGN KEY (task_id)
REFERENCES skent.task (task_id) MATCH SIMPLE
ON UPDATE CASCADE
ON DELETE NO ACTION;

ALTER TABLE IF EXISTS skent.assignment
ADD CONSTRAINT fk_user FOREIGN KEY (user_id)
REFERENCES skent.user (user_id) MATCH SIMPLE
ON UPDATE CASCADE
ON DELETE NO ACTION;

-- Assign tasks to Max or user_id = 1
INSERT INTO skent.assignment
(
    user_id,
    task_id
)
VALUES 
(1,1),
(1,2),
(1,3),
(1,5),
(1,8),
(1,9),
(1,10),
(1,11);

-- Assign tasks to Sander or user_id = 2
INSERT INTO skent.assignment
(
    user_id,
    task_id
)
VALUES 
(2,1),
(2,2),
(2,3),
(2,6),
(2,7),
(2,8),
(2,9),
(2,10),
(2,11);

-- Assign tasks to Julian or user_id = 3
INSERT INTO skent.assignment
(
    user_id,
    task_id
)
VALUES 
(3,1),
(3,2),
(3,3),
(3,4),
(3,8),
(3,9),
(3,10),
(3,11);

--Assigned tasks for a user | change user_id = 1
SELECT * FROM skent.task t
JOIN skent.assignment a
ON t.task_id = a.task_id
WHERE a.user_id = 1;
